before:
  hooks:
    - go mod tidy
    - go generate ./...
project_name: unifi
builds:
  - main: ./cmd/unifi_cli
    id: "unifi_cli"
    binary: unifi-cli
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'